// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Dispatch.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Dispatch
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ForceUpdateInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"force_update_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ForceUpdateUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StopServerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"content_msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ContentMsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Url { get; set; } = "";

        [global::ProtoBuf.ProtoMember(1, Name = @"stop_begin_time")]
        public uint StopBeginTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"stop_end_time")]
        public uint StopEndTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResVersionConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(7, Name = @"next_script_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NextScriptVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"branch")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Branch { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"version_suffix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VersionSuffix { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"md5")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Md5 { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"release_total_size")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ReleaseTotalSize { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"relogin")]
        public bool Relogin { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        public uint Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegionInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(30, Name = @"user_center_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserCenterUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(19, Name = @"client_data_md5")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientDataMd5 { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"resource_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResourceUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(16, Name = @"handbook_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string HandbookUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(20, Name = @"client_silence_data_md5")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientSilenceDataMd5 { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"area_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AreaType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(1, Name = @"gateserver_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GateserverIp { get; set; } = "";

        [global::ProtoBuf.ProtoMember(23, Name = @"secret_key")]
        public byte[] SecretKey { get; set; }

        [global::ProtoBuf.ProtoMember(34, Name = @"next_resource_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NextResourceUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(35, Name = @"next_res_version_config")]
        public ResVersionConfig NextResVersionConfig { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"official_community_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OfficialCommunityUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(31, Name = @"account_bind_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccountBindUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"pay_callback_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PayCallbackUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"resource_url_bak")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResourceUrlBak { get; set; } = "";

        [global::ProtoBuf.ProtoMember(22, Name = @"res_version_config")]
        public ResVersionConfig ResVersionConfig { get; set; }

        [global::ProtoBuf.ProtoMember(36, Name = @"game_biz")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GameBiz { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"feedback_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeedbackUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(27, Name = @"client_silence_version_suffix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientSilenceVersionSuffix { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"data_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DataUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(26, Name = @"client_version_suffix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientVersionSuffix { get; set; } = "";

        [global::ProtoBuf.ProtoMember(33, Name = @"privacy_policy_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PrivacyPolicyUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13, Name = @"data_url_bak")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DataUrlBak { get; set; } = "";

        [global::ProtoBuf.ProtoMember(29, Name = @"gateserver_domain_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GateserverDomainName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"bulletin_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BulletinUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(32, Name = @"cdkey_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CdkeyUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(28, Name = @"use_gateserver_domain_name")]
        public bool UseGateserverDomainName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"gateserver_port")]
        public uint GateserverPort { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"client_data_version")]
        public uint ClientDataVersion { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"client_silence_data_version")]
        public uint ClientSilenceDataVersion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegionSimpleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"dispatch_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DispatchUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Title { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QueryRegionListHttpRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(6, Name = @"client_custom_config_encrypted")]
        public byte[] ClientCustomConfigEncrypted { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"client_secret_key")]
        public byte[] ClientSecretKey { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"region_list")]
        public global::System.Collections.Generic.List<RegionSimpleInfo> RegionLists { get; } = new global::System.Collections.Generic.List<RegionSimpleInfo>();

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public int Retcode { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"enable_login_pc")]
        public bool EnableLoginPc { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QueryCurrRegionHttpRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"force_udpate")]
        public ForceUpdateInfo ForceUdpate
        {
            get => __pbn__detail.Is(4) ? ((ForceUpdateInfo)__pbn__detail.Object) : default;
            set => __pbn__detail = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeForceUdpate() => __pbn__detail.Is(4);
        public void ResetForceUdpate() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__detail, 4);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__detail;

        [global::ProtoBuf.ProtoMember(5, Name = @"stop_server")]
        public StopServerInfo StopServer
        {
            get => __pbn__detail.Is(5) ? ((StopServerInfo)__pbn__detail.Object) : default;
            set => __pbn__detail = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeStopServer() => __pbn__detail.Is(5);
        public void ResetStopServer() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__detail, 5);

        [global::ProtoBuf.ProtoMember(3, Name = @"region_info")]
        public RegionInfo RegionInfo { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"client_secret_key")]
        public byte[] ClientSecretKey { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"region_custom_config_encrypted")]
        public byte[] RegionCustomConfigEncrypted { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"client_region_custom_config_encrypted")]
        public byte[] ClientRegionCustomConfigEncrypted { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public int Retcode { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
